os: linux
language: python
python: 3.6

env:
  global:
    # Doctr deploy key for slaclab/edm2pydm
    - secure: "EJZZC55r4K81f33tfmdiJJGEDf1VYIkxkLosbFKAUdbjV9uZvYZFofHEUyl8h84EiYOcD4yZL2ZYAIuVv6SYhBEZjRiJqZa2Qs+VxrA2OlvHsKfS/rb5B4KMmKIHQkdPGDESLQT/zH+MdtpqSrUvg63GqqssBgpZJYeVEgh6A6xQ7yOw9jSznO7OMXAn7YX3aSioeQ6ggA2t/YtflcQt6fFbmBVWok1IzV6yP33VHwiTLb9YKaSdDv8+ovdDz7Cev/ZkAT15eYlVBYIBc1P1PScoZdGYC6uggvv2MFrpeu1VHkVNGUlMpiGYDa/UQOwW51GG1jCCcrcTAD20gZs9rP4a8yk/320N+PrPpckgi6rArPeidldma+aG87KlFHCRptD5UggkFfHwRYdYqwfH7HDosI9/4YVVpcWOHohGw3J1NXmp77kacpoOs987B7Q2tMhFAw8QS9P7BwQYPGpoUlKixq5F/LjhXX2xzmhEpbomN81HJiO/xYhF120ECZFwmyDawwMMmwjda6LRJlvmWg4b5rf5tmgzqg5JhFRjpgut+JnXedl9dBUUyIaKmxg+LEr6Bf3ESrJrxghP8Y5ruGqNHI92QysNz+RInriXdsj+ldIQYD7rwcUok4bPB6xJo5isjsjSWgCsD3gQ73GwbgGOEUjPpX7f3o/sT74TuWQ="

script:
  #Build docs
  - set -e
  - |
    if [[ -n "$DOCTR_DEPLOY_ENCRYPTION_KEY_SLACLAB_PYDM_TUTORIAL" ]]; then
      pip install -r docs-requirements.txt
      pushd docs
      make html
      popd
      #Publish docs.
      doctr deploy . --built-docs docs/build/html --deploy-branch-name gh-pages
    fi
